---
- name: Get Instance Data
  include: get_instance_data.yml



- name: Add tags if tags var is set
  include: set_missing_always_up_flag_to_false.yml
  when: set_tags

- name: Set fact for notification
  set_fact:
    body: "{{ lookup('template', 'base_notification.j2') }}"
  vars:
    header: "The following instances were untagged and have had AlwaysUp tag set to false"
  when: set_tags

- name: Shut down instances if shutdown var is set
  include: shutdown_instances.yml
  when: nightly_shutdown

- name: Set fact for notification
  set_fact:
    body: "{{ lookup('template', 'base_notification.j2') }}"
  vars:
    header: "The following instances did not have AlwaysUp set to True and will be shutdown"
  when: nightly_shutdown

- name: Delete instances if delete_over_30 var is set
  include: shutdown_over_30.yml
  when: shutdown_over_30

- name: Set fact for notification
  set_fact:
    body: "{{ lookup('template', 'base_notification.j2') }}"
  vars:
    header: "The following machines have been shutdown over 30 days and have been deleted"
  when: shutdown_over_30

   
- name: Print out affected machines
  debug:
    msg: "{{ body.split('\n')}}"
  when: instances
